name: e2e Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "13"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lua-tests:
    name: e2e (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    # e2e tests could be flaky on CI so we do not block release creation if they failed
    continue-on-error: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
        with:
          cache: true
          cache-on-failure: false
          cache-key: "v2-lua-e2e"
          rustflags: ""

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build Rust binary
        run: cargo build --release -p fff-nvim --features zlob

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.10.4

      - name: Clone plenary.nvim
        shell: bash
        run: git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim

      - name: Run Lua tests
        shell: bash
        run: make test-lua

      - name: Run version resolution tests
        shell: bash
        run: make test-version

      - name: Run bun tests
        shell: bash
        run: make test-bun

      - name: Install Node.js
        if: ${{ matrix.os != 'ubuntu-latest' }}
        uses: actions/setup-node@v6
        with:
          node-version: "25"

      - name: Install node dependencies
        shell: bash
        run: cd packages/fff-node && npm install

      - name: Run node tests
        shell: bash
        run: make test-node
